# Generated by Django 6.1.1 on 2026-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="tipo_peluquero",
            field=models.CharField(
                choices=[
                    ("ESPECIFICO", "Peluquero específico"),
                    ("CUALQUIERA", "Cualquier peluquero"),
                ],
                default="CUALQUIERA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("CANCELADA", "Cancelada"),
                    ("COMPLETADA", "Completada"),
                    ("CONFIRMADA", "Confirmada"),
                    ("PENDIENTE", "Pendiente"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
