# Generated by Django 6.1.1 on 2026-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0004_alter_cita_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("COMPLETADA", "Completada"),
                    ("PENDIENTE", "Pendiente"),
                    ("CANCELADA", "Cancelada"),
                    ("CONFIRMADA", "Confirmada"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
