# Generated by Django 6.1.1 on 2026-10-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0008_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
    ]
