# Generated by Django 6.1.1 on 2026-10-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0009_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario de atención',
                'verbose_name_plural': 'Horarios de atención',
                'ordering': ['dia_semana'],
            },
        ),
    ]
