# Generated by Django 6.1.1 on 2026-10-11 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(choices=[('INICIO', 'Inicio'), ('MENU', 'Menú principal'), ('SERVICIOS', 'Elegir servicios'), ('ELEGIR_DIA', 'Elegir día'), ('ELEGIR_FRANJA', 'Elegir mañana o tarde'), ('ELEGIR_HORA', 'Elegir hora'), ('ELEGIR_TIPO_PELUQUERO', 'Elegir tipo de peluquero'), ('ELEGIR_PELUQUERO', 'Elegir peluquero'), ('CONFIRMAR_CITA', 'Confirmar cita'), ('ELEGIR_CITA_CANCELAR', 'Elegir cita a cancelar'), ('CONFIRMAR_CANCELACION', 'Confirmar cancelación')], default='INICIO', max_length=30)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversacion_whatsapp', to='Clients.cliente')),
            ],
            options={
                'verbose_name': 'Conversación de WhatsApp',
                'verbose_name_plural': 'Conversaciones de WhatsApp',
            },
        ),
    ]
