# Generated by Django 6.1.1 on 2026-10-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacionwhatsapp',
            old_name='client',
            new_name='cliente',
        ),
    ]
