# Generated by Django 6.1.1 on 2026-10-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsApp', '0002_rename_client_conversacionwhatsapp_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacionwhatsapp',
            old_name='actualizado_en',
            new_name='actualizado',
        ),
    ]
