# Generated by Django 6.1.1 on 2026-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=12, unique=True)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
